{% set name = "pyprojroot" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "a79900dc52ee097bfd8d917a3d45e2b98494c47a57ba3a71bf609d7a156732e8"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pathlib

test:
  imports:
    - pyprojroot
    - tests

about:
  home: "https://github.com/chendaniely/pyprojroot"
  license: "MIT"
  license_family: "MIT"
  license_file: LICENSE
  summary: "Find project root paths and return relative project files"

extra:
  recipe-maintainers:
    - jamesmyatt
    - philip-khor
